from discord import Colour, Embed
import datetime
import random

async def element_color(element):
    switch = {
        'Light': Colour.gold(),
        'Dark': Colour.dark_purple(),
        'Fire': Colour.dark_red(),
        'Water': Colour.dark_blue(),
        'Forest': Colour.dark_green()
    }
    return switch.get(element)


async def child_embed(row):
    em = Embed(color=await element_color(row["element"]), description=row["rank"])
    em.title = row["name"]
    em.add_field(name="Role", value=row["role"], inline=True)
    em.add_field(name="Element", value=row["element"], inline=True)
    em.add_field(name="Leader Skill", value=row["leader_skill"], inline=False)
    em.add_field(name="Auto Skill", value=row["auto_skill"], inline=False)
    em.add_field(name="Tap Skill", value=row["tap_skill"], inline=False)
    em.add_field(name="Slide Skill", value=row["slide_skill"], inline=False)
    em.add_field(name="Drive Skill", value=row["drive_skill"], inline=False)
    if row["notes"] is not None:
        em.set_footer(text=row["notes"], icon_url="https://i.imgur.com/zcJGvMI.png")
    if row["thumbnail"] is not None:
        em.set_thumbnail(url=row["thumbnail"])
    if row["image"] is not None:
        em.set_image(url=row["image"])

    return em


async def quote_embed(row):
    em = Embed(title=row['invoke'], color=Colour.dark_blue())

    if row['text'].startswith("http") or row['text'].startswith(" http"):
        em.set_image(url=row["text"])
    else:
        em.description = (row["text"])

    return em


async def quote_info(ctx, row):
    em = Embed(title=row['invoke'], color=Colour.dark_blue())

    if row['text'].startswith("http") or row['text'].startswith(" http"):
        em.set_thumbnail(url=row["text"])
    else:
        em.description = (row["text"])

    if row['user_id']:

        member = ctx.guild.get_member(row['user_id'])
        
        if member:
            display = member.display_name
            em.set_author(name='Tag info', icon_url=member.avatar_url)
        else:
            display = row['created_by']

        em.add_field(name='Created by', value=display, inline=True)

    elif row['created_by']:
        em.add_field(name='Created by', value=row['created_by'], inline=True)

    if row['created_at']:
        date = row['created_at']
        em.add_field(name='Created at', value=f'{date:%d. %B %Y : %H:%M:%S}', inline=True)

    return em


async def coin_embed(url):
    em = Embed(colour=Colour.dark_blue())
    em.set_image(url=url)
    return em


async def wb_ticket_reset():
    em = Embed(title="Ticket Reset!", description=':alarm_clock: @here Ticket reset! :alarm_clock:', timestamp=datetime.datetime.utcnow())
    em.set_footer(text="Use ?wb stop if world boss is dead.")
    return em


gacha_phrases = [
    'Ameno.',
    "I'll not do this again.",
    "Don't mind me, i'm a dunce.",
    "Get cucked bro.",
    "Get shit on.",
    "Oof",
    "Gotcha Bitch!",
    "**CENSORED**",
    "Mission failed, we'll get em  next time.",
    "I won't do this again.",
    "I deserved this.",
    "No one liked you anyways",
    "The bs level in this message was higher than the allowed quota",
    "It was gibberish anyways ¯\_(ツ)_/¯",
    "Would be a shame if I ate your message",
]


async def kirinus_gacha(message):
    if random.randrange(1, 100) < 4:
        await message.delete()
        await message.channel.send(random.choice(gacha_phrases))
    else:
        return None


def pendulum_to_datetime(pendulum):
    dt_time = datetime.datetime(pendulum.year, pendulum.month, pendulum.day, pendulum.hour, pendulum.minute,
                                pendulum.second, pendulum.microsecond, pendulum.timezone)
    return dt_time


insult_phrases = [
"Because rexaGod wanna kills all of Christians",
"You're an inspiration for birth control.",
"You should let your chair play, at least it knows how to support.",
"There are about 37 trillion cells working together in your body right now, and you are disappointing every single one of them.",
"I'm not trash talking, I'm talking to trash",
"Friendly fire was invented because of you",
"Did you know sharks only kill 5 people each year? Looks like you got some competition",
"You're the type of player to get 3rd place in a 1v1 match",
"You're living proof that God has a sense of humour",
"I would unplug your life support to charge my phone.",
"Stephen Hawking has better hand-eye coordination than you.",
"You should turn the game off. Just walk outside and find the nearest tree, then apologise to it for wasting so much oxygen.",
"I regret not smoking my entire life, because watching you still gave me cancer.",
"The only problem with your PC is that thing between your keyboard and your chair",
"I'd call you cancer, but at least cancer gets kills.",
"I don't have the time or the crayons to explain this to you.",
"You have some big balls on you. Too bad they belong to the guy fucking you from behind.",
"It's just a joke not a dick, don't take it so hard.",
"I'd tell you to kill yourself, but I'm pretty sure you'd miss.",
"You're lucky your dad's dick had better aim than you.",
"A million years of evolution and we get you.",
"Two wrongs don't make a right, take your parents as an example.",
"I'd love to see things from your perspective, but I don't think I could shove my head that far up my ass.",
"i bet the last time u felt a breast was in a kfc bucket",
"I'd call you cancer, but cancer gets kills.",
"Legend has it that the number 0 was first invented after scientists calculated your chance of doing something useful.",
"You're the human equivalent of a participation award.",
"You must have been born on a highway, because that's where most accidents happen",
"I would call you cancer but cancer actually gets kills",
"Abraham Lincoln can dodge bullets better than you.",
"That crosshair is for aiming at enemies, you know.",
"I bet your brain feels as good as new, seeing that you never use it.",
"Two wrongs don't make a right, take your parents for instance",
"I'd call you a tool, but that would imply you were useful in at least one way.",
"Does your ass ever get jealous of the amount of shit that comes out of your mouth?",
"It's kinda sad watching you attempt to fit your entire vocabulary into one sentence.",
"You could be the only person in the game and still manage to die.",
"I would insult you but nature did a better job.",
"I would mentally duel with you, but I can see you're unarmed",
"If only you could hit an enemy as much as your dad hits you.",
"You could shoot at the ground and still miss",
"Calling you a retard is a compliment in comparison to how stupid you actually are.",
"Wow, this game should really be R-rated. I'm looking at the killfeed and all it shows is our team getting fucked.",
"Maybe God made you a bit too special.",
"I'm jealous of all the people who have never met you.",
"Believe in yourself, because the rest of us think you're an idiot.",
"I'm jealous of people that don't know you.",
"I'm surprised that you were able hit the 'Install' button",
"I'm not saying I hate you, but I would unplug your life support to charge my phone.",
"You're the reason they need to put instructions on shampoo bottles.",
"If it wasn't for gravity you couldn't even hit the fucking ground",
"When your mother took you to school for the first time she was fined for littering",
"I'm not saying you're useless, but I'd unplug your router to charge my phone.",
"I'm sure your bodypillow is very proud of you.",
"Does your ass ever get jealous of the amount of shit that comes out of your mouth",
"The only thing you carry is an extra chromosome",
"Your family tree is a cactus, because everybody on it is a prick.",
"You know what they say, whatever doesn't kill you is just a surprise to the rest of us.",
"You're the reason the gene pool needs a lifeguard.",
"Why is it acceptable for you to be terrible, but not for me to point it out?",
"Christopher Columbus has better map awareness than you",
"Some babies were dropped on their heads but you were clearly thrown at a wall",
"You should apologize to every tree you see for wasting their oxygen",
"It's a joke, not a cock. Stop taking it hard.",
"I would tell you to shoot yourself, but you'd miss.",
"I could swallow bullets and shit out a better spray than that",
"You would make a perfect stormtrooper.",
"It's a joke, not a cock, don't take it so hard.",
"If life is like a box of chocolates, you're a fucking raisin",
"You're about as useful as a snowshovel in Hawaii.",
"To which foundation do I need to donate to help you?",
"It must be difficult for you, exhausting your entire vocabulary in one sentence.",
"I'd tell you to shoot yourself, but I bet you'd miss",
"I need an apology letter. Can I borrow your birth certificate?",
"I'm surprised you even hit the power button on your computer.",
"You know what man, blind gamers deserve a chance too. I support you.",
"If only you could hit an enemy as much as your dad hits you.",
"If you got cancer, I would feel bad for the cancer.",
"Why don't you slip into something more comefortable? Like a coma?",
"I bet your club penguin pets killed themselves",
"You must have been born on a highway because that's where most accidents happen.",
"You're the reason why no religion has a god that stays on Earth.",
"If you want to hear about mistakes, ask your parents.",
"I'm sure you exist only because the other sperm felt bad.",
"Internet Explorer could run faster than you",
"At least your ping knows how to high score.",
"Your birth certificate is an apology letter from the condom factory.",
"I'd call my team cancer, but at least cancer kills.",
"When I die I want you to to lower me in my grave so you can let me down one more time.",
"You didn't make a mistake. Your parents did.",
"Its a shame you werent the pilot of 9/11, you would have missed the building.",
"The only thing you are carrying is an extra chromosome",
"Correct! I am a tool, because unlike you, I'm actually useful.",
"Safest place for us to stand is in front of your gun",
"I'd tell you to just end it and shoot yourself, but you'd probably miss.",
"Your Tinder profile has seen more lefts than a Nascar track",
"You can start trying any time you like.",
"You make stormtroopers look good.",
"If I wanted to kill myself I'd jump from your ego down to your IQ.",
"I'd like to see things form your point of view, but I can't get my head that far up my ass.",
"I'd tell you to blow me but you've been sucking dick all game",
"I suggest turning your monitor on for improved gaming performance.",
"Does your ass get jealous of the shit that comes out of your mouth?",
"I would ask if you were new, but that would imply you can actually get better",
"Ah yes, the Dead Sea, the second saltiest thing on Earth next to your bitch ass.",
"I have neither the time, nor the crayons, to explain this to you.",
"Some people get paid to suck, you do it for free.",
"I've seen better reflexes from Bethesda NPCs",
"When I die, I'd like you to lower my coffin, so you can let me down one last time.",
"I'd call all of you cancer, but at LEAST cancer kills.",
"I've had more engaging arguments with my dog",
"I bet you're that guy that dies in the tutorial.",
"Don't worry, everybody was new once. You just... stayed.. new, somehow...",
"I see you gained a new hobby, Collecting Bullets.",
"You're the reason abortion was legalized",
"The keys your looking for are Alt-F4",
"I could eat a bowl of alphabet soup and shit out a smarter statement than that.",
"Did your parents try to get a refund?",
"I'm pretty sure you've typed more sentences than landed shots.",
"Hitler knew when to kill-himself. Why can't you do the same?",
"Do you believe in God ? cause he dosn't believe in you.",
"I'd tell you to kill yourself, but chances are you'd fuck that up too",
"If this was pay-to-win, you'd go bankrupt before you got your first kill.",
"What's higher, your IQ or your age?",
"Might I suggest you beat the tutorial first",
"Try switching your router off, that might help.",
"If you were any more inbred you'd be a sandwich",
"I'd tell you where the uninstall button is but you'd miss that one too",
"Imagine going through 9 months of pregnancy to give birth to a child who doesn't do the fucking objective.",
"I guess the abortion clinic forgot one",
"aww, you're just like Jesus, always respawning and never hurting anyone :)",
"I'd call you an ape, but that'd give them more of a reason to shoot Harambe again.",
"I would insult you, but my parents always told me not to abuse the profoundly handicapped.",
"You should try your luck at russian roulette, at least you might kill something",
"You couldn't hit water if you fell out of a boat.",
"With that aim, I'm impressed you could even hit the queue button.",
"The ocean must be jealous from the amount of salt you hold.",
"I must be Noah's Ark. I'm carrying a bunch of fucking animals",
"imagine going through 9 months of pregnancy to give birth to a child who doesn't push the fucking payload.",
"I'd agree with you, but then we'd both be wrong",
"I would slap you, but that would be animal abuse",
"If we learn from our mistakes, your parents must be geniuses now",
"I'd tell you to go outside, but you'd just ruin that for everyone else too",
"Remember, riding dick is not a mode of transportation.",
"Why don't you check between your chair and your keyboard for the problem?",
"I have neither the time nor the crayons to explain this to you.",
"You're as useful as Stephen Hawking's home gym",
"With that poor aim, im surprised your dad figured out where to stick it in",
"Keep rolling your eyes, maybe you'll find a brain back there",
"I can't wait till I have dementia so I can forget that ever happened.",
"What's the difference between you and a bench? The bench can actually support an entire team.",
"It's a joke, not a cock, don't take it so hard",
"You're like an onion. On the outside you're shit, but peel away a layer and underneath is another layer of shit",
"Mistakes were made, the worst one was by your parents.",
"You must really like that respawn timer",
"ergkirhrjrl;asewi    shit, sorry, my cat walked on my keyboard and somehow it still played better than you.",
"I recommend you keep crying. It's the only thing you're doing right.",
"I wonder if you last as long in bed as you do in this game.  I'd ask your girlfriend, but hands can't talk.",
"31.5 N, 35,5 E, the coordinates of the Dead Sea, the saltiest place on earth next to your bitch ass.",
"Your years of practice on easy bots clearly paid off.",
"I would ask you how old you are but I know you can't count that high.",
"Were you born on a freeway? Because that's where most accidents happen.",
"You are the reason why abortion is legal.",
"Are you trying to beat the sea in a salt contest? That's probably the only thing you're winning right now.",
"Perhaps your strategy should include trying.",
"If you stopped jerking off, maybe the blood would go to your brain instead.",
"Good job keeping your learning curve perfectly horizontal.",
"You might help your future win-rate by uninstalling.",
"God ran out of clay, so he slapped a bunch of dog shit together to make you",
"You're the reason they need to put instructions on Bleach bottles",
"Shutting-the-fuck-up is also gluten free, why not add that to your diet?",
"Guys, can we put the bots on a higher difficulty?",
"Now I know why nearly every game has arrows pointing to the objective. They were all for you.",
"I'd call your aim cancer, but at least cancer can kill people.",
"If laughter is the best medicine, your face must be curing the world.",
"Go down to the nearest drugstore and buy a little thing called viagra. It will help you go fuck yourself.",
"How'd you get through the tutorial?",
"Maybe if you spent as much effort on the game as do bitching, you might actually kill something other than my will to live.",
"You're as useful as a white crayon",
"Who set the bots to passive?",
"I was anti-abortion before I started this match but now I'm reconsidering.",
"With aim like that, I pity whoever has to clean the floor around your toilet",
"Does your ass get jealous of all the shit that comes out of your mouth?",
"Your aim is proof that excessive masturbation causes blindness",
"Your aim is so shit you couldn't hit the ground if you fell",
"The only thing that will ever fuck you, is life.",
"It's sad that your IQ matches your shoe size.",
"When i die i want you guys to lower my coffin so you can let me down one more time",
"There are vacuum cleaners that suck less than you.",
"You're worth less than a Steam trading card",
"I didn't know dying was a special ability.",
"I could eat alphabet soup and still shit out a better argument than you.",
"How the fuck were you the fastest sperm???!",
"I think you should just go afk. You'd get better results.",
"I'm okay with this team. I work in the city as a garbage collector. I'm used to carrying trash.",
"I had no expectations for you and yet you still managed to disappoint. Bravo.",
"You are the MVP of the other team.",
"Your parents aren't the only ones who regret knowing you",
"it was a joke, not a dick, don't take it so hard..",
"Don't worry guys, I am a trash man IRL. I am used to carry garbage like you",
"You're living testament to the idea that people only use 10% of their brains",
"Your birth certificate is an apology from the condom factory.",
"	 I bet you guys are going to single-handedly keep the porn industry alive for the next 30 years the way you're fucking us.",
"You are probably the only person that will miss with an aimbot.",
"Does your mouse have recoil or something?",
"I'd call you cancer but at least cancer can kill things",
"Your asshole must be jealous of all the shit that comes out of your mouth.",
"players like you should come with a handicap sticker",
"Only thing you're carrying is an extra chromosome.",
"If your dad's aim was as good as yours we wouldn't be talking right now.",
"What language are you speaking? Cause it sounds like bullshit.",
"I would call you cancer, but cancer actually kills people.",
"Your aim is so poor, even African countries feel the need to donate to you.",
"The only thing you've killed this game is my faith in you.",
"It's incredible how you can bring so many people so much joy just by leaving the game!",
"I love a good sale, but ain't nobody buying your bullshit.",
"Sorry, I lied. I called you cancer, but then I remembered that cancer acually kills people..",
"Letting you live was medical malpractice",
"Team Fortress 2 is also Free-To-Uninstall",
"With a score as low as that, you must be amazing at golf.",
"Shut up, you'll never be the man your mother is.",
"If you listen closely, you can actually hear the salt crystals forming",
"Try not to trip on your skill level on the way out.",
"You know this isn't turn based combat right? When they shoot at you feel free to shoot back.",
"Your ass must be jealous of all that shit coming out of your mouth",
"Two wrongs don't make a right, like your parents.",
"only thing u carry is an extra chromosome",
"Don't beat yourself up. We already did that for you.",
"You must really like spectating your team",
"I don't know what your problem is, but I bet its hard to pronounce",
"If you were to shoot yourself, your K/D ratio would improve by 100%.",
"Do you ever wonder what life would be like if you'd had enough oxygen at birth?",
"Stephen Hawking did great with his disability. Why can't you?",
"I`d call you cancer, but cancer actually gets kills",
"You can turn on your monitor now.",
"Oh look, Hitler missed one",
"I can't carry you with all those extra chromosomes weighing you down.",
"Your family tree must be a circle",
"Kirby must be jealous with how much you suck.",
"Your aim is so poor that people held a fundraiser for it",
"You are a walking condom advertisment.",
"I noticed your sister got all the good genes from the family.",
"Whoever told you to just be yourself couldn't have given you worse advice",
"The keys you're looking for are Alt-F4",
"Maybe you should try something more on your level, like rock-paper-scissors.",
"i don't know what gets less hits... your aim or your online dating profile",
"'Three-second burst' should be your rate-of-fire, not your life expectancy",
"You must have been born on a highway, because that's where most accidents happen.",
"I'd try to see things from your point of view but I couldn't get my head that far up my ass.",
"John Lennon is better at dodging bullets than you",
"You look like someone pressed the randomize button in the Oblivion character creator.",
"Too bad you weren't in control of the Titanic. You would have missed the Iceberg.",
"Stairs has killed more people than you have.",
"30 millon sperm and you swam the fastest?",
"Stephen Hawkings probably runs better than your game",
"Out of any animal you identify with, you chose a bitch.",
"Hey, give me a shoutout to your 2 Twitch viewers",
"You shouldn't play hide and seek, no one would look for you.",
"Just because you have the ability to click play doesn't mean you should.",
"It is dangerous to use your whole vocabulary in one sentence.",
"Can't hear you from the bottom of the scoreboard",
"The way you're feeding, Africa may finally have a chance.",
"Do your parents cry every day or just on the days they realize they didn't get the abortion?",
"Kennedy dodges bullets better than you do.",
"I'd call this team cancer, but at least cancer gets kills.",
"If I wanted to listen to an asshole, I'd fart",
"Your reaction time is on par with the time it takes for plastic to decompose.",
"You're the reason your dad drinks",
"You're supposed to be farming gold, not chromosomes.",
"Have you considered pointing that gun the other way around?",
"I'd tell you to kill yourself but you probably couldn't even manage that",
"Try playing the game normally, instead of just repeatedly slamming your forehead into the keyboard.",
"\_/ <- Cry here, Africa needs water.",
"I'd agree with you, but then we'd both be wrong.",
"I used to be an athiest but only divine intervention could create something as miserable as you.",
"No this isn't Pay-To-Win, all you have to do is pay attention",
"I bet you would blame it on the lag at a LAN party too.",
"How many tries did it take for you to click the install button?",
"A woman at a urinal has better spray control than you",
"I cant hear you at the bottom of the scoreboard",
"You are a living contradiction to evolution.",
"If your face was a Counter Strike map, it would be de_formed.",
"please look at the screen when you are playing",
"If I wanted to kill myself, I would climb up to your ego, and jump down to your IQ level.",
"Imagine that someone was pregnant for nine months, gave birth, and their child doesn't even play the fucking objective.",
"You might as well start hacking, that way you could finally achieve something; a ban.",
"have you ever had a conversation where the other person wasn't just shaking their head in disappointment?",
"Fuck yourself. You'll finally get some pussy that way.",
"stop hogging all the deaths",
"It's dangerous to use your entire vocabulary in a single sentence!!!",
"Players like you are why Easy mode is a difficulty option.",
"How are you this bad at support? Do you work for Comcast?",
"I'd insult you, but my mother told me not to insult the handicapped.",
"The only game you could get a high score in is golf.",
"I'd make a joke, but you're already here",
"Stevie Wonder can see how shit you are",
"I'd call you a piece of shit but that at least has use as fertilizer",
"If I wanted to kill myself I'd climb your ego and jump to your IQ.",
"With an aim like that, I'm surprised you were able to turn your PC on.",
"My vacuum cleaner is sucking less than you.",
"You're the kind of guy who could lose to the maze on the back of a cereal box.",
"You're a prime example of why the gene pool needs a whole lot of bleach",
"Isn't your time running out on the library computer?",
"What's the biggest difference between you and Hitler? At least Hitler managed to kill himself.",
"I'm not questioning your intelligence, merely denying its existence",
"I'd call you cancer, but it kills.",
"Fighting on the internet is like participating in the paralympics. Even if you win, you're still retarded.",
"I've never touched a cigarette. I feel a sense of regret for not doing it, because you gave me cancer anyway.",
"Your existence is the reason for scientists to rethink the plausibility of evolution.",
"You'd have made an excellent Stormtrooper",
"A fucking flight of stairs has killed more people than you have",
"Only thing you carry is an extra chromosome.",
"Imagine going through a nine month pregnancy only to give birth to someone who can't push the fucking cart.",
"Aiming can increase your accuracy.",
"Team Fortress 2 is also Free-To-Uninstall,",
"It'd be an insult to compare a stormtrooper to you. At least they know what they're trying to shoot at.",
"You aim like a hamster with parkinson's who's high on cocaine on the top floor of the World Trade Center during an earthquake",
"Why don't you slip into something more comfortable...like a coma.",
"If you're going to be two-faced, at least make one of them pretty.",
"You are as useless as a white crayon",
"Imagine going through 9 months of pregnancy just to give birth to a child who doesn't push the fucking payload",
"This team could lose at Farmville.",
"I'd tell you to commit suicide, but then you'd have a kill.",
"You are more ignored than Terms and Services.",
"If you ever win a match screencap and send to the church. Pretty sure that'll count as a miracle.",
"Were you always this shitty or you're trying really hard today?",
"Are you constipated? 'cause you ain't doin' shit.",
"Stormtroopers hit their targets more than you.",
"You remind me of the last batch of scrambled eggs I made: beaten, over-salted, and burned.",
"I'm still not convinved God exists, but if he does you prove he has a sense of humor.",
"It seems you and the kill cam have become well acquainted",
"I'd insult your mother, but I'd hurt your sister's feelings.",
"If you really want to know about mistakes, you should ask your parents.",
"Your mother should've spent the money on an abortion rather than the booze she drank during the pregnancy.",
"What you lack in brain cells, you make up for in chromosome count.",
"When I die I want you guys to lower my coffin so you can let me down one last time.",
"Imagine what your life would be if your parents weren't siblings.",
"If I got a dollar every time you missed a shot i could buy you the glasses you so desperately need.",
"Your existance is proof people don't know how to pull out.",
"If you'd been the terrorist piloting the jet in 9/11, the towers would probably still be there",
"Don't worry guys, I'm a garbage collector. I'm used to carrying trash.",
"You have worse map awareness than Christopher fucking Columbus.",
"**PROTIP** Your crosshair generally assists you in aiming.",
"The way you're feeding, you could end world hunger.",
"Stormtroopers aim better than you.",
"I'd like to see things from your prespective, but I can't seem to get my head that far up your ass.",
"Two men walk into a bar. You walk into a fucking pole.",
"If I wanted to kill myself, I would climb up to your ego and jump down to your IQ level",
"Your skill is like John Cena, nobody can see it",
"Imagine going through 9 months of pregnancy only to give birth to someone who decides to be the fucking fourth spy on the team.",
"You couldn't pour water out of a boot if the instructions were on the heel",
"If ignorance is bliss, you must be the happiest person on earth.",
"My shoes have more support than you've given me.",
"if i wanted to kill myself id jump from your ego to your IQ",
"Your parents deserve more than this.",
"You guys answered the age-old question of whether God could create a team of people so dense that even he could not carry them",
"Comcast gives better support than you.",
"Your idea of a comeback is jerking off into a fan",
"Maybe you should try something more your speed.. like stopping",
"You know your team is trying to win right?",
"Not even Noah could carry these animals.",
"You're that one guy that would actually get his dick stuck in a ceiling fan for not following instructions.",
"I'd call you cancer, but at least cancer kills.",
"If ignorance is bliss you must be the happiest person alive.",
"Are you AFK? Good, we finally have a chance of winning.",
"The guy who played CSGO with a wheel is better than you",
"I think you should press the power button in order to contribute to the game.",
"I was going to make a joke about your kills but I couldn't find any.",
"I used to think everyone had the potential to be great, then I discovered you.",
"Your existence is the best argument against intelligent design.",
"Your parents need to get a very late term abortion",
"Warmup ended several rounds ago.",
"If I wanted to get yelled at by folks like you, I would go to the daycare.",
"This game has a wide variety of playable characters and playstyles, and I'd appreciate it if you'd learn one.",
"I hope you're the last person in a human centipede.",
"I bet you have alot of participation awards...",
"You could win an oscar for how sad your life is.",
"Most people missed out on the lottery, you missed out on the gene pool.",
"The way you feed, you could stop world hunger.",
"You are proof enough that guns do not kill people.",
"You are proof that evolution CAN go in reverse.",
"Could you imagine what it would have been like if you had more oxygen at birth",
"Do you lose when you play against yourself too?",
"I'm jealous of people that didnt know you.",
"If you killed as much people as made excuses, you would've topped the scoreboard by now.",
"Does your brain run on Internet Explorer?",
"If you were on fire and I had water, I'd drink it.",
"Next round, you should try looking at the monitor.",
"Is your ass jealous of the amount of shit that just came out of your mouth?",
"You probably think the light in the refrigerator never turns off.",
"There are loads of tutorials online that will show you how to setup your mouse properly.",
"Do you have parkinson's or do you just aim like shit?",
"I've seen obese Mexican food vendors push carts better than this team.",
"Why don't you ever get out of the basement? Did you break the stairs while trying?",
"You're a failed abortion whose birth certificate is an apology from the condom factory.",
"If I was your dad I would run away too.",
"The only thing lower than your k/d ratio is your I.Q.",
"You remind me of the son I never wanted",
"All of these flavors and you choose to be salty",
"Why are you still here? I thought trash day was yesterday.",
"You failed, just like your dad's condom",
"Can you please check if your mouse is plugged in?",
"Does your mouse have kickback when you shoot?",
"Your aim is so poor Obama made a plan for it.",
"Let's just let natural selection take it's course",
"I think you need to talk to your doctor about Type 2 Diabetes. You seem to be consuming a lot of salt.",
"even the steam support is more useful than you",
"you're topping the scoreboard in chromosome count",
"Do Irish guys pick you up and get really excited that they found a Potato?",
"I hope you step on a lego",
"Play with a blindfold on, at least you'll have a valid reason for missing all those shots.",
"Looking at you, I understand why some animals eat their young.",
"If you were a real terrorist, the world would be a much safer place.",
"I wonder if you'd be able to play better if your parents were second cousins instead of first.",
"Shouldn't you be trying to put a round block in a square hole somewhere?",
"It's quick, it's easy, and it's free: Trying.",
"I bet you blame the lag even when you're playing with bots.",
"If I wanted to kill myself I'd jump from your ego down to your rank",
"I appreciate you letting us win a few rounds to make it fair, but you can start trying now.",
"I wish we'd met years ago, I would have repressed the memory by now",
"I'm Sorry I Can't Hear you From the Bottom of the Scoreboard",
"You know that if you plug the screen in you can actually see the enemies.",
"Eat your veggies kids, that's how I got strong enough to carry you all",
"The killcam ran out of film thanks to you.",
"Holy shit! You're not just useless, you're harmless too!",
"If you were any dumber I would have to water you twice a day",
"Well I would agree with you but then we'd both be wrong",
"You're the reason negatives numbers exist",
"Maybe Hello Kitty Island Adventure is more around your skill level",
"You're baiting so hard you could probably catch a fucking shark",
"My toaster comes up with better burns than you do.",
"I know you're trying your best, but I wish your best was actually trying.",
"It's not that I hate you, you just don't deserve respect in the first place.",
"The only thing you can hit is your dignity",
"just do exactly the opposite of everything you think and we might have a chance",
"I have bowel movements that move faster than your thought process",
"I believed in the good and potential of humanity. And then you came along.",
"I'm surprised you even managed to get out of bed without hurting yourself",
"Were you born on the highway, cause that's where all the accidents happen.",
"If I had a dollar for every time you missed a shot I could buy you the glasses you so desperately need.",
"I was pro-life until I met you.",
"I'm trying to see this from your perspective, but I can't seem to get my head that far up my own ass.",
"Jesus shouldn't have died for this.",
"At least your immune system tries to stop you from dying.",
"Maybe if you try to miss, you might hit something!",
"I'd trade you for a park bench, at least it could support the team",
"Wait, don't go. I still need more salt on my food.",
"You're literally welfare to the other team.",
"I would tell you a joke, but your entire existance makes a better job at that than me.",
"Oops, I must have chosen easy bots by accident",
"Salt may be a solid but damn do you make it flow",
"Your mother is so ugly people break into your house just to close the curtains",
"If I gave you a penny for your thoughts how much change would I get back?",
"At least terminal cancer gets kills.",
"Can you just place your cat on the keyboard and leave? We've a better chance of winning that way.",
"I guess my team is sponsored by the Make-A-Wish foundation...",
"Mentally challenged people don't want to be referred as 'Retarded' becuase they don't want to be compared with you.",
"If you die and your life flashes before your eyes, how much are you gonna see of you not pushing the payload?",
"Did Marvel buy the rights to your mouse?  Because you can't seem to actually kill anybody off.",
"If only all terrorists were like you... the world would be much safer.",
"If I wanted to kill myself, I'd climb your ego and jump to your IQ.",
"How did you ever get through the tutorial level?",
"Remember that it's better to try and fail than to not try at all, so don't be afraid to start trying any time now",
"video games bring new experiences and right now I'm experiencing what it's like to be a special needs caretaker",
"You have less brain cells than your kill count.",
"Imagine how much better you would be if your monitor was on.",
"At least your ping score is higher than mine",
"Wow, you're more toxic than the beaches at Fukushima.",
"You're the type of person who would miss at point blank range with a flamethrower.",
"You bring down the property value just being here.",
"If you honestly call that trying, you're not even a candidate for the participation award.",
"does your ass ever get jealous of all the shit that comes out of your mouth?",
"Wow, do you kiss your cousin with that mouth?",
"I'd tell you to go play in traffic, but you'd probably suck at that too.",
"If I jumped from your ego to your intelligence, I'd die of starvation half-way down.",
"I'd suggest you to uninstall the game but I bet it's too complex for you",
"Since i am able to talk to you, people call me the trash whisperer",
"I would call you cancer, but cancer kills",
"Let your mom play. At least she knows how to push",
"I'm not even insulting you, just accurately describing you",
"When you go to a family reunion, who brings the condoms?",
"I've seen more support for North Korea than I've seen all game from you.",
"Retards are just impersonating you",
"Your reaction time is as fast as coastal erosion.",
"Does your ass ever get jealous of the amount of shit that comes from your mouth?",
"You lost the game for us? Don't worry, everyone makes mistakes, even God does, we have you to show for it!",
"I'd say your aim is cancer, but cancer is getting people killed.",
"I would kill myself to get away from you, but you would probably follow me.",
"You must of been born on a highway. Because that's where most accident's happen",
"Some babys were dropped on there heads, but you were clearly thrown at a wall.",
"I've killed spiders that put up more of a fight than you fucks.",
"I would say go to hell, but not even the devil deserves to deal with you",
"Not even Noah needed to carry this many animals.",
"The only thing that you can hit is rock-bottom.",
"i'm surprised you know how to breath",
"The only way you'll ever get laid is if you crawl up a chicken's ass and wait.",
"You are the best argument for intelligent design, for only a deity could have created a being as pathetic as you",
"I would call you cancer, but at least cancer kills",
"Don't talk out loud. You lower the IQ of the entire street.",
"I'm not going easy on you! That's the mistake your parents made!",
"When i die i want you guys to lower my coffin so you can let me down once more",
"Your birth certificate is a reciept for Trojan Condoms.",
"You talk so much shit, I'm not sure to offer you a breath mint or toilet paper.",
"If you stood next to a trash can, somebody would ask if you were twins",
"The only thing you carry is an extra chromosome!",
"Don't talk out loud you lower the iq of the entire street",
"i want to roast you, but burning trash is bad for the enviroment",
"You're the type of person to suck dick for bus money and then walk home.",
"What great sin did I do to know you?",
"If I had a cent for everytime you hit a shot I would somehow be homeless and in debt",
"If your IQ was money, I couldn't even buy a gumball.",
"reported your mom for giving birth to you",
"Ahhh...I see the fuck-up fairy has visited us again...",
"Your IQ matches room temperature in Celsius.",
"I'd teach you how to tie a noose, but you'd probably fuck that up too.",
"I bet you probably buy chocolates for yourself on Valentine's Day.",
"I'd call you cancer, but atleast cancer kills.",
"If I had two bullets and I was in a room with you and Hitler I would shoot you twice",
"You're so salty, if I gave you a bag of chips, it would be cannibalism.",
"I wasn't aware it was possible to kill the walls more then the actual enemies.",
"i bet the last time u felt a breast was in a kfc bucket'",
"Bill Gates just called me, you aim is so poor that he wants to donate to it",
"If you were any more inbred, you'd be a fucking sandwich.",
"I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
"You're so bad that you make my cat stepping on my keyboard look like a pro gamer.",
"I thought everyone one in the world was beautiful then I looked at you and realized I was wrong",
"It's gonna' be really shocking to your parents if you end up getting anything past a two-digit paycheck after college.",
"The Crusades were started for political reasons too, but at least they accomplished something in the long run.",
"Not even the Priest would molest you.",
"I'd make a joke, but you're already here.",
"If I had a dollar for every shot you missed, I could monopolize the entire stock market.",
"You are so trash that if you became a garbage collector, the trash itself would carry you to the garbage truck.",
"You are proof that evolution is bullshit",
"I know why you're so dumb. Your brain is the same size as your penis.",
"I'd say your aim is cancer, but cancer actually kills people.",
"I'm sorry, not even the TARDIS can translate your stupidity",
"Wow! Imagine if your parents weren't siblings!",
"Use your head as a suppressor next time.",
"the only way you'd get laid is if u stuck your head up a chicken's ass and waited",
"The only difference between you and Hitler is Hitler did something with his life.",
"I bet you walk into a server and lower the average IQ.",
"if i had a penny for everytime you hit, i would be in debt",
"If I was allergic to stupidity I'd be blown up like a balloon around you.",
"You're the result of a failed abortion.",
"I found less toxicity in Chernobyl in 1986",
"You'd make a killing doing chalk lines with how great you outline your enemies.",
"Studies show that aiming gives you better chances of hitting your target.",
"I could get buff carrying your deadweight.",
"I'd call you cancer but at least get some kills first.",
"you have more chins than a chinese phonebook",
"The only thing killing me is your stupidity",
"It sucks to know adoption centres don't have a refund policy.",
"How much dick do you suck? It's like you constantly feel the need to open your mouth",
"Your penis is like the McDonalds ice cream machine, It's always broken.",
"Your ass should be jealous of all the shit coming out of your mouth.",
"Don't you love nature, despite what it did to you?",
"You have the same map awareness as Christopher Columbus.",
"I've seen downies with parkinsons have better tracking than you.",
"You're proved that you're even more useless than the sales director of WinRAR.",
"It looks like your face caught on fire and someone tried to put it out with a fork.",
"The only thing that you can hit is the accept button.",
"You are proof that abortions dont work",
"You could only be more of an ass if you were an actual donkey.",
"The only aid you provide is the disease.",
"If you were more inbred, you'd be a sandwich!",
"I'd call you trash but that would be a complement",
"I?m glad your dad beat you, and not cancer.",
"Im not talking trash im talking to trash",
"I'd carry you, but  my back would break from your fatass.",
"I could eat alphabet soup and shit out a better arguement than that",
"Bitch. You fail just like your daddy's condom did!",
"The only thing more unreliable than you is the condom your dad used.",
"Opposites attract, like your IQ and ego",
"You need to get a hearing aid because you didn't hear the enemy's gunfire right behide you.",
"I'd castrate you but you don't have any balls",
"Your parents would have been better off if your mom swallowed.",
"Shock me, say something intelligent.",
"Imagine going through nine painful months of pregnancy to give birth to a child who doesn't push the fucking payload.",
"Here i thought everything had a purpose, But when i saw you, Clearly you were a mistake.",
"Is your birth certificate an apology letter from the condom factory?",
"Do you want some fries with that salt?",
"If salt was a type of currency, you would be the main contributor to inflation.",
"Helen Keller has better observational awareness than you"
]


async def random_insult(ctx):
        em = Embed(description=f"{ctx.message.mentions[0].mention}. {random.choice(insult_phrases)}")
        em.set_footer(text=ctx.author.display_name, icon_url=ctx.author.avatar_url)
        await ctx.message.delete()
        await ctx.message.channel.send(embed=em)

